added testnet20 changes
massalabs/massa-web3 pull request #118
Opened 2023-02-26 23:13 UTC by BatiGencho

2023-02-27 08:58 UTC, Thykof requested changes

2023-02-27 08:58 UTC, Thykof commented on examples/smartContracts/index.ts
> +  'S12srNEAvZrTb9pktYeuePpuM4taW5dfmWAZYtdqyETWTBspkoT1';
it's a bad practice to have secrets in the code

2023-02-27 08:58 UTC, Thykof commented on src/interfaces/IOperationData.ts
> +    id: string; //
either fill the comment or remove `//`

```suggestion
    id: string;
```

2023-02-27 10:19 UTC, BatiGencho commented on src/interfaces/IOperationData.ts
>    in_pool: boolean; //
annotated

2023-02-27 10:19 UTC, BatiGencho commented on src/interfaces/IOperationData.ts
> +    id: string; //
annotated

2023-02-27 10:20 UTC, BatiGencho commented on src/web3/BaseClient.ts
> +        ]);
refactored and pulled out into a smaller func

2023-02-27 17:12 UTC, BatiGencho commented on examples/wallet/index.ts
> +  'S12srNEAvZrTb9pktYeuePpuM4taW5dfmWAZYtdqyETWTBspkoT1';
agree, I have moved the priv keys etc. to an .env file

2023-02-27 17:19 UTC, Thykof requested changes
1. Can you add .env file in gitignore?
2. there are duplicated code in examples, for retriving env vars, maybe it's for the example to be clearer
3. you are updating yarn lock and package lock, you have to choose :) which one yarn or npm you want to use, or maybe I miss something. For all others projects we use npm and it works well.

2023-02-28 09:47 UTC, Thykof approved these changes
make sure to never used the wallet of the private key in the .env.example

2023-02-28 12:50 UTC, merged