138 add ci to the smart contract example
massalabs/massa-web3 pull request #141
Opened 2023-04-28 08:34 UTC by Elli610

2023-05-10 06:57 UTC, gregLibert approved these changes

2023-05-10 06:57 UTC, gregLibert commented on .github/workflows/deploy-test-smartContract.yml
> +      - name: build
```suggestion
      - name: Build
```

2023-05-10 06:58 UTC, gregLibert requested changes
Sorry bad action. Can you take into account my comment from the previous review ?

2023-05-10 13:50 UTC, gregLibert approved these changes

2023-05-12 16:39 UTC, gregLibert commented
@Elli610 the CI has failed

2023-05-14 17:43 UTC, Ben-Rey commented
@Elli610 The Ci need to be fixed

2023-05-17 13:06 UTC, merged