Update the interfaces documentation : EOperationStatus (included) -> IContractData (included)
massalabs/massa-web3 pull request #149
Opened 2023-05-02 06:59 UTC by windushka

Aims to solve  #147

2023-05-04 08:29 UTC, Elli610 requested changes

2023-05-04 08:29 UTC, Elli610 commented on src/interfaces/IBlockcliqueBlockBySlot.ts
> + * address, block ID, and operations.
For now I do not have the knowledge to review this. I'll learn about blockclique and edit this comment later today.

2023-05-04 08:29 UTC, Elli610 commented on src/interfaces/ICallData.ts
> + * This interface is used to track the call data information, including the
```suggestion
 * This interface is used to track the calldata information, including the
```

2023-05-04 08:29 UTC, Elli610 commented on src/interfaces/IClient.ts
> + * Represents the main client interface for interacting with the blockchain.
```suggestion
 * Represents the client object.
```

2023-05-04 08:29 UTC, Elli610 commented on src/interfaces/IClient.ts
> + * APIs, wallet, and smart contracts. It also provides methods for setting
This is not clear

2023-05-04 08:29 UTC, Elli610 commented on src/interfaces/IClientConfig.ts
> + * Represents the configuration for the main client interface.
```suggestion
 * This interface is used to configure the client 
```

2023-05-04 08:29 UTC, Elli610 commented on src/interfaces/IClique.ts
> + * indicating a better block clique.
```suggestion
 * - This interface is used to track a block clique, including the block IDs,
 * the fitness of the clique, and whether it is a valid block clique. 
 * - Fitness is a measure of the quality of a block clique, with a higher fitness value
 * indicating a better block clique.
```

2023-05-04 08:29 UTC, Elli610 commented on src/interfaces/IContractData.ts
> + * @see maxGas of type `bigint` represents the maximum gas that can be consumed by the smart contract.
is this the max gas fees that can be consumed during the deployment or while calling it ?

2023-05-04 08:29 UTC, Elli610 commented on src/interfaces/IContractData.ts
> + * @see contractDataText of type `string | undefined` represents the contract's data as text (optional).
```suggestion
 * @see contractDataText of type `string | undefined` represents the contract's data as string (optional).
```

2023-05-05 07:30 UTC, Elli610 approved these changes

2023-05-11 06:09 UTC, Ben-Rey approved these changes

2023-05-11 06:10 UTC, merged