update Baseclient.ts documentation
massalabs/massa-web3 pull request #153
Opened 2023-05-02 08:07 UTC by Elli610

related to #152

2023-05-05 12:46 UTC, 0xSwapFeeder requested changes

2023-05-05 12:46 UTC, 0xSwapFeeder commented on src/web3/BaseClient.ts
> +   *  @returns The provider for the rpc method
```suggestion
   * @returns The provider for the rpc method
```

2023-05-05 12:46 UTC, 0xSwapFeeder commented on src/web3/BaseClient.ts
> +   * @returns A promise that resolves as a JsonRpcResponseData
```suggestion
   *
   * @returns A promise that resolves as a JsonRpcResponseData
```

2023-05-05 12:46 UTC, 0xSwapFeeder commented on src/web3/BaseClient.ts
> +   * @return The compacted bytes payload
```suggestion
   *
   * @return The compacted bytes payload
```

2023-05-05 15:07 UTC, 0xSwapFeeder approved these changes

2023-05-09 07:43 UTC, Ben-Rey approved these changes

2023-05-09 07:48 UTC, Ben-Rey commented
@Elli610 can you check why the CI Fail ?

2023-05-09 12:42 UTC, merged