Update PublicApiClient.ts
massalabs/massa-web3 pull request #159
Opened 2023-05-02 11:30 UTC by Elli610

related to #152

2023-05-04 09:24 UTC, Ben-Rey requested changes

2023-05-11 07:09 UTC, 0xSwapFeeder requested changes
Watch your ts doc tags !

2023-05-11 07:09 UTC, 0xSwapFeeder commented on src/web3/PublicApiClient.ts
> +   * @return A promise which resolves in the blockclique details
```suggestion
   *
   * @return A promise which resolves in the blockclique details
```

2023-05-11 07:09 UTC, 0xSwapFeeder commented on src/web3/PublicApiClient.ts
> +   * @return A promise which resolves in the addresses data
```suggestion
   *
   * @return A promise which resolves in the addresses data
```

2023-05-11 07:09 UTC, 0xSwapFeeder commented on src/web3/PublicApiClient.ts
> +   * @return A promise which resolves in the block data
```suggestion
   *
   * @return A promise which resolves in the block data
```

2023-05-11 07:09 UTC, 0xSwapFeeder commented on src/web3/PublicApiClient.ts
> +   * @return A promise which resolves in the operation data
```suggestion
   *
   * @return A promise which resolves in the operation data
```

2023-05-11 07:09 UTC, 0xSwapFeeder commented on src/web3/PublicApiClient.ts
> +   * @return A promise which resolves to the datastore entries
```suggestion
   *
   * @return A promise which resolves to the datastore entries
```

2023-05-14 14:44 UTC, Ben-Rey approved these changes

2023-05-14 16:10 UTC, gregLibert approved these changes

2023-05-15 09:42 UTC, 0xSwapFeeder approved these changes

2023-05-15 09:42 UTC, merged