docs(interfaces): added documentation for Private Api Client interface
massalabs/massa-web3 pull request #163
Opened 2023-05-02 13:30 UTC by 0xSwapFeeder

Aims to resolve #156.

2023-05-03 07:14 UTC, Elli610 commented
you forgot to run prettier

2023-05-04 12:24 UTC, Elli610 approved these changes

2023-05-04 14:22 UTC, gregLibert requested changes

2023-05-04 14:22 UTC, gregLibert commented on src/interfaces/IPrivateApiClient.ts
> +   * @returns - A promise so that the call can be asynchronous.
Is it normal that we don't knon if the action was successful or not ?

2023-05-04 14:22 UTC, gregLibert commented on src/interfaces/IPrivateApiClient.ts
> + * @interface IPrivateApiClient
Can you fixe Ci warning ?

2023-05-05 08:57 UTC, gregLibert commented on src/interfaces/IPrivateApiClient.ts
> +   * @returns - A promise so that the call can be asynchronous.
J'ai  fumé, désolé

2023-05-05 08:57 UTC, gregLibert approved these changes

2023-05-05 08:58 UTC, merged