improved converters.ts doc
massalabs/massa-web3 pull request #178
Opened 2023-05-02 15:41 UTC by windushka

aims to solve #166

2023-05-05 07:16 UTC, Elli610 approved these changes

2023-05-05 07:16 UTC, Elli610 commented on src/utils/converters.ts
> + * Convert any value expressed in Massa back to nanoMassa.
Is nanoMassa the smallest unit ? If so we can precise it

2023-05-05 07:16 UTC, Elli610 commented on src/utils/converters.ts
> + * Massa is a unit of currency and nanoMassa is a sub-unit, where 1 Massa equals 10^9 nanoMassa.
Is nanoMassa the smallest unit ? If so we can precise it

2023-05-05 12:26 UTC, Elli610 approved these changes

2023-05-11 08:02 UTC, 0xSwapFeeder requested changes

2023-05-11 08:02 UTC, 0xSwapFeeder commented on src/utils/converters.ts
> + * @returns The amount expressed in nanoMassa, as a bigint.
```suggestion
 *
 * @returns The amount expressed in nanoMassa, as a bigint.
```

2023-05-11 08:02 UTC, 0xSwapFeeder commented on src/utils/converters.ts
> + * @returns The amount expressed in Massa, as a BigNumber.
```suggestion
 *
 * @returns The amount expressed in Massa, as a BigNumber.
```

2023-05-12 13:24 UTC, 0xSwapFeeder approved these changes
lgtm

2023-05-15 06:33 UTC, Ben-Rey approved these changes

2023-05-15 06:34 UTC, merged