172 index doc
massalabs/massa-web3 pull request #183
Opened 2023-05-03 07:35 UTC by windushka

aims to solve #172

2023-05-04 07:20 UTC, Elli610 commented on src/utils/serializers/index.ts
> + */
```suggestion
/**
 * This module exports encoding and decoding functions for strings.
 */
```
we should keep it simple

2023-05-04 07:23 UTC, Elli610 commented on src/utils/serializers/index.ts
> + * handle signed and unsigned integers, as well as BigInt for 64-bit integers.
```suggestion
 * This module exports functions needed to process numeric data, such as integers and 
 * floating point numbers and their binary representations in Uint8Array. 
 * The functions handle signed and unsigned integers, as well as BigInt for 64-bit integers.
```

2023-05-04 07:27 UTC, Elli610 commented on src/utils/serializers/index.ts
> + * and other nested arrays.
```suggestion
 * This module exports serialization and deserialization functions for arrays containing native types.
```
same here

2023-05-04 07:31 UTC, Elli610 requested changes
changes needed

2023-05-05 07:35 UTC, Elli610 requested changes
The @throws should be located between @param and @returns, check notion

2023-05-05 08:00 UTC, Elli610 approved these changes

2023-05-05 08:00 UTC, Elli610 commented on src/utils/serializers/numbers.ts
> + *
```suggestion
```

2023-05-11 08:07 UTC, 0xSwapFeeder approved these changes

2023-05-15 06:43 UTC, Ben-Rey approved these changes

2023-05-15 06:46 UTC, merged