Update time.ts
massalabs/massa-web3 pull request #185
Opened 2023-05-03 07:47 UTC by Elli610

closes #168

2023-05-04 11:09 UTC, 0xSwapFeeder requested changes

2023-05-04 11:09 UTC, 0xSwapFeeder commented on src/utils/time.ts
> + * @param timeMilli - The time interval in milliseconds.
```suggestion
 * @param timeMilli - The time interval in milliseconds.
 *
```

2023-05-04 11:09 UTC, 0xSwapFeeder commented on src/utils/time.ts
> + * @param timeoutMs - The time interval in milliseconds.
Not sure the @throws is correctly placed relative to other TSDoc tags, read the notion.
```suggestion
 * @param timeoutMs - The time interval in milliseconds.
 
```

2023-05-09 14:42 UTC, 0xSwapFeeder approved these changes

2023-05-11 06:22 UTC, Ben-Rey approved these changes

2023-05-11 06:24 UTC, merged