Update Xbqcrypto.ts
massalabs/massa-web3 pull request #186
Opened 2023-05-03 07:56 UTC by Elli610

closes #169

2023-05-03 09:24 UTC, Ben-Rey requested changes

2023-05-03 09:24 UTC, Ben-Rey commented on src/utils/Xbqcrypto.ts
>  import { signedBigIntUtils, unsignedBigIntUtils } from './encode_decode_int';
```suggestion
/**
 * A collection of utility functions for working with various data encoding and hashing formats.
 * 
 * This module provides several functions for encoding and decoding data in various formats, including
 * `base58`, `varint`, and `blake3 hashes`.
 * 
 * @module Xbqcrypto.ts
 */

import { signedBigIntUtils, unsignedBigIntUtils } from './encode_decode_int';
```

2023-05-03 09:24 UTC, Ben-Rey commented on src/utils/Xbqcrypto.ts
> + * The varint encoding is a variable length encoding of integers.
```suggestion
 * Encodes a number or bigint to a varint encoded Uint8Array.
```

2023-05-04 07:22 UTC, Ben-Rey approved these changes

2023-05-04 07:28 UTC, gregLibert approved these changes

2023-05-10 07:29 UTC, merged