Update bool.ts
massalabs/massa-web3 pull request #188
Opened 2023-05-03 08:21 UTC by Elli610

closes #171

2023-05-04 13:32 UTC, 0xSwapFeeder requested changes

2023-05-04 13:32 UTC, 0xSwapFeeder commented on src/utils/serializers/bool.ts
> + * @return {boolean} the converted boolean
This is type script TSDoc so no JSDoc type annotation required, and stop forgetting the new line between different tags types :sweat_smile:

2023-05-04 13:32 UTC, 0xSwapFeeder commented on src/utils/serializers/bool.ts
> + * @return {Uint8Array} the converted Uint8Array
Same

2023-05-11 06:30 UTC, Ben-Rey approved these changes

2023-05-11 07:06 UTC, 0xSwapFeeder approved these changes
lgtm

2023-05-11 07:36 UTC, Ben-Rey approved these changes

2023-05-11 07:36 UTC, merged