add contributing
massalabs/massa-web3 pull request #204
Opened 2023-05-09 07:30 UTC by Elli610

closes #151

2023-05-09 14:45 UTC, 0xSwapFeeder requested changes
Formatting seems awkward, way to many blank lines I think.
Otherwise lgtm.

2023-05-14 17:56 UTC, Ben-Rey approved these changes

2023-05-15 09:15 UTC, gregLibert approved these changes

2023-05-15 09:15 UTC, gregLibert commented on CONTRIBUTING.md
> +
```suggestion
```

2023-05-15 09:15 UTC, gregLibert commented on CONTRIBUTING.md
> +
```suggestion
```

2023-05-15 09:15 UTC, gregLibert commented on CONTRIBUTING.md
> +
```suggestion
```

2023-05-15 09:17 UTC, merged