261 setup test environment
massalabs/massa-web3 pull request #262
Opened 2023-06-06 09:32 UTC by julienbrs

closes #261
branch #257 can be deleted

2023-06-06 15:56 UTC, Ben-Rey requested changes

2023-06-06 15:56 UTC, Ben-Rey commented on test/web3/walletClient.spec.ts
> +describe('WalletClient', () => {
```suggestion
describe.skip('WalletClient', () => {
```

2023-06-06 15:56 UTC, Ben-Rey commented on test/web3/walletClient.spec.ts
> +describe('WalletClient', () => {
We skip it until we find a solution to run test on buildnet

2023-06-06 15:59 UTC, Ben-Rey approved these changes

2023-06-09 15:54 UTC, gregLibert approved these changes

2023-06-09 15:54 UTC, merged