Refactor verifySignature code
massalabs/massa-web3 pull request #378
Opened 2023-06-29 15:17 UTC by julienbrs

closes #286 

Implements static method to create a public key from a base58encoded string and find the version number from it.
Refactor some code thanks to that

2023-07-04 06:11 UTC, Ben-Rey commented on src/utils/keyAndAdresses.ts
> +  /* Static method to create a public key from a base58 encoded string, and decoding the version number */
```suggestion
  // Create a new PublicKy object from a base58 encoded string
```

2023-07-04 21:13 UTC, Ben-Rey requested changes

2023-07-04 21:13 UTC, Ben-Rey commented on src/utils/keyAndAddresses.ts
> +  // Create a new PublicKy object from a base58 encoded string
```suggestion
  // Create a new PublicKey object from a base58 encoded string
```

2023-07-04 21:13 UTC, Ben-Rey commented on src/utils/keyAndAddresses.ts
> + * @remarks bytes is not an attribute of the address object because it is not needed.
It's best to have one remarks with multiple points:

```typescript
@remarks
    - first remark
    - second
    ...
```

2023-07-05 12:34 UTC, Ben-Rey approved these changes

2023-07-07 09:36 UTC, gregLibert requested changes

2023-07-07 09:36 UTC, gregLibert commented on src/utils/keyAndAddresses.ts
> +    const versionAndKeyBytes = getBytesPublicKey(publicKeyBase58Encoded);
```suggestion
  static fromString(base58Encoded: string): PublicKey {
    const versionAndKeyBytes = getBytesPublicKey(base58Encoded);
```

2023-07-07 10:26 UTC, gregLibert approved these changes

2023-07-07 10:26 UTC, merged